repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        files: ^smartsim/
        exclude: ^tests/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
        additional_dependencies: [mypy>=1.3.0, types-psutil, types-redis, types-tabulate, types-tqdm, types-tensorflow==2.12.0.9, types-setuptools, typing_extensions>=4.1.0, pydantic==1.10.14, pyzmq==25.1.2]
        files: ^smartsim/
        exclude: ^tests/
        args: [--config-file=./pyproject.toml]