# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
      # You can add any other files or directories that you'd like here as well,
      # like your docs requirements file, or other files that will change your docs build.
      #
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- doc/ .readthedocs.yaml;
        then
          exit 183;
        fi
      - git clone --depth 1 https://github.com/CrayLabs/SmartRedis.git smartredis
      - git clone --depth 1 https://github.com/CrayLabs/SmartDashboard.git smartdashboard
      - pwd
      - python -m pip install -e .[dev,docs]
      - cd smartredis; python -m pip install .
      - cd smartredis/doc; doxygen Doxyfile_c; doxygen Doxyfile_cpp; doxygen Doxyfile_fortran
      - ln -s smartredis/examples ./examples
      - cd smartdashboard; python -m pip install .
      - smart build --device cpu --dragon -v
      - |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(dirname $(find $PWD -name "libdragon.so")) &&
        echo $LD_LIBRARY_PATH &&
        make docs &&
        mkdir -p _readthedocs/ &&
        cp -r doc/_build/html/ _readthedocs/
      - pip install typing_extensions==4.8.0
      - pip install pydantic==1.10.13
      - python -m sphinx -b linkcheck doc/ $READTHEDOCS_OUTPUT/linkcheck
      

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
