codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    patch:
      default:
       # Account for some variability in codecov
       target: 0%
    project:
      default:
       # Account for some variability in codecov
       target: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default # update comment if already exists, otherwise post new
  require_changes: no
  require_base: no
  require_head: yes
