
[smartsim]
# number of seconds per job status update
# for jobs on WLM system (e.g. slurm, pbs, etc)
jm_interval = 15    # default
log_level = "info" # default

[redis]
# path to where "redis-server" and "redis-cli" binaries are located
bin = "/path/to/redis/src/"
config = "/path/to/redis.conf" # optional!

  [redis.modules]
  ai = "/path/to/RedisAI/install-cpu/"

[test]
launcher = "local" # default
interface = "ib0" # network interface to use in tests
device = "CPU" # device to use for tests (CPU/GPU)
