services:
  docs-dev:
    image: smartsim-docs:dev-latest
    build:
      context: .
      dockerfile: ./docker/docs/dev/Dockerfile

  tutorials-dev:
    image: smartsim-tutorials:dev-latest
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8888:8888"

  tutorials-prod:
    image: smartsim-tutorials:v0.8.0
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "8888:8888"
