#!/bin/sh

# Based on running mpiexec.slurm without loading a specific MPI
# implementation 

echo "
Usage:
    mpiexec.slurm args executable pgmargs

    where args are comannd line arguments for mpiexec (see below),
    executable is the name of the eecutable and pgmargs are command line
    arguments for the executable. For example the following command will run
    the MPI program a.out on 4 processes:

            mpiexec.slurm -n 4 a.out

    mpiexec.slurm supports the following options:

             [-n nprocs]
             [-host hostname]
             [-verbose]
             [-nostdin]
             [-allstdin]
             [-nostdout]
             [-pernode]
             [-config config_file]
             [-help|-?]
             [-man]
"
