"""This is an automatically generated stub for `response_attributes.capnp`."""

from __future__ import annotations

from contextlib import contextmanager
from io import BufferedWriter
from typing import Iterator

class TorchResponseAttributes:
    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> Iterator[TorchResponseAttributesReader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> TorchResponseAttributesReader: ...
    @staticmethod
    def new_message() -> TorchResponseAttributesBuilder: ...
    def to_dict(self) -> dict: ...

class TorchResponseAttributesReader(TorchResponseAttributes):
    def as_builder(self) -> TorchResponseAttributesBuilder: ...

class TorchResponseAttributesBuilder(TorchResponseAttributes):
    @staticmethod
    def from_dict(dictionary: dict) -> TorchResponseAttributesBuilder: ...
    def copy(self) -> TorchResponseAttributesBuilder: ...
    def to_bytes(self) -> bytes: ...
    def to_bytes_packed(self) -> bytes: ...
    def to_segments(self) -> list[bytes]: ...
    def as_reader(self) -> TorchResponseAttributesReader: ...
    @staticmethod
    def write(file: BufferedWriter) -> None: ...
    @staticmethod
    def write_packed(file: BufferedWriter) -> None: ...

class TensorflowResponseAttributes:
    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> Iterator[TensorflowResponseAttributesReader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> TensorflowResponseAttributesReader: ...
    @staticmethod
    def new_message() -> TensorflowResponseAttributesBuilder: ...
    def to_dict(self) -> dict: ...

class TensorflowResponseAttributesReader(TensorflowResponseAttributes):
    def as_builder(self) -> TensorflowResponseAttributesBuilder: ...

class TensorflowResponseAttributesBuilder(TensorflowResponseAttributes):
    @staticmethod
    def from_dict(dictionary: dict) -> TensorflowResponseAttributesBuilder: ...
    def copy(self) -> TensorflowResponseAttributesBuilder: ...
    def to_bytes(self) -> bytes: ...
    def to_bytes_packed(self) -> bytes: ...
    def to_segments(self) -> list[bytes]: ...
    def as_reader(self) -> TensorflowResponseAttributesReader: ...
    @staticmethod
    def write(file: BufferedWriter) -> None: ...
    @staticmethod
    def write_packed(file: BufferedWriter) -> None: ...
