# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartsim_protobuf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartsim_protobuf.proto',
  package='SmartSimProtobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17smartsim_protobuf.proto\x12\x10SmartSimProtobuf\"\x1c\n\x0cScalarUInt32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\r\"\x1c\n\x0cScalarUInt64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x04\"\x1c\n\x0cScalarSInt32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x11\"\x1c\n\x0cScalarSInt64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x12\"\x1b\n\x0bScalarFloat\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\"\x1c\n\x0cScalarDouble\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x01\"6\n\x0b\x41rrayUInt32\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\rB\x02\x10\x01\"6\n\x0b\x41rrayUInt64\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x04\x42\x02\x10\x01\"6\n\x0b\x41rraySInt32\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x11\x42\x02\x10\x01\"6\n\x0b\x41rraySInt64\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x12\x42\x02\x10\x01\"5\n\nArrayFloat\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x02\x42\x02\x10\x01\"6\n\x0b\x41rrayDouble\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x01\x42\x02\x10\x01\x62\x06proto3'
)




_SCALARUINT32 = _descriptor.Descriptor(
  name='ScalarUInt32',
  full_name='SmartSimProtobuf.ScalarUInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarUInt32.data', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=73,
)


_SCALARUINT64 = _descriptor.Descriptor(
  name='ScalarUInt64',
  full_name='SmartSimProtobuf.ScalarUInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarUInt64.data', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=103,
)


_SCALARSINT32 = _descriptor.Descriptor(
  name='ScalarSInt32',
  full_name='SmartSimProtobuf.ScalarSInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarSInt32.data', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=133,
)


_SCALARSINT64 = _descriptor.Descriptor(
  name='ScalarSInt64',
  full_name='SmartSimProtobuf.ScalarSInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarSInt64.data', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=163,
)


_SCALARFLOAT = _descriptor.Descriptor(
  name='ScalarFloat',
  full_name='SmartSimProtobuf.ScalarFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarFloat.data', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=192,
)


_SCALARDOUBLE = _descriptor.Descriptor(
  name='ScalarDouble',
  full_name='SmartSimProtobuf.ScalarDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ScalarDouble.data', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=222,
)


_ARRAYUINT32 = _descriptor.Descriptor(
  name='ArrayUInt32',
  full_name='SmartSimProtobuf.ArrayUInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArrayUInt32.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArrayUInt32.data', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=278,
)


_ARRAYUINT64 = _descriptor.Descriptor(
  name='ArrayUInt64',
  full_name='SmartSimProtobuf.ArrayUInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArrayUInt64.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArrayUInt64.data', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=334,
)


_ARRAYSINT32 = _descriptor.Descriptor(
  name='ArraySInt32',
  full_name='SmartSimProtobuf.ArraySInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArraySInt32.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArraySInt32.data', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=390,
)


_ARRAYSINT64 = _descriptor.Descriptor(
  name='ArraySInt64',
  full_name='SmartSimProtobuf.ArraySInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArraySInt64.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArraySInt64.data', index=1,
      number=2, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=446,
)


_ARRAYFLOAT = _descriptor.Descriptor(
  name='ArrayFloat',
  full_name='SmartSimProtobuf.ArrayFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArrayFloat.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArrayFloat.data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=501,
)


_ARRAYDOUBLE = _descriptor.Descriptor(
  name='ArrayDouble',
  full_name='SmartSimProtobuf.ArrayDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimProtobuf.ArrayDouble.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimProtobuf.ArrayDouble.data', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=557,
)

DESCRIPTOR.message_types_by_name['ScalarUInt32'] = _SCALARUINT32
DESCRIPTOR.message_types_by_name['ScalarUInt64'] = _SCALARUINT64
DESCRIPTOR.message_types_by_name['ScalarSInt32'] = _SCALARSINT32
DESCRIPTOR.message_types_by_name['ScalarSInt64'] = _SCALARSINT64
DESCRIPTOR.message_types_by_name['ScalarFloat'] = _SCALARFLOAT
DESCRIPTOR.message_types_by_name['ScalarDouble'] = _SCALARDOUBLE
DESCRIPTOR.message_types_by_name['ArrayUInt32'] = _ARRAYUINT32
DESCRIPTOR.message_types_by_name['ArrayUInt64'] = _ARRAYUINT64
DESCRIPTOR.message_types_by_name['ArraySInt32'] = _ARRAYSINT32
DESCRIPTOR.message_types_by_name['ArraySInt64'] = _ARRAYSINT64
DESCRIPTOR.message_types_by_name['ArrayFloat'] = _ARRAYFLOAT
DESCRIPTOR.message_types_by_name['ArrayDouble'] = _ARRAYDOUBLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScalarUInt32 = _reflection.GeneratedProtocolMessageType('ScalarUInt32', (_message.Message,), {
  'DESCRIPTOR' : _SCALARUINT32,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarUInt32)
  })
_sym_db.RegisterMessage(ScalarUInt32)

ScalarUInt64 = _reflection.GeneratedProtocolMessageType('ScalarUInt64', (_message.Message,), {
  'DESCRIPTOR' : _SCALARUINT64,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarUInt64)
  })
_sym_db.RegisterMessage(ScalarUInt64)

ScalarSInt32 = _reflection.GeneratedProtocolMessageType('ScalarSInt32', (_message.Message,), {
  'DESCRIPTOR' : _SCALARSINT32,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarSInt32)
  })
_sym_db.RegisterMessage(ScalarSInt32)

ScalarSInt64 = _reflection.GeneratedProtocolMessageType('ScalarSInt64', (_message.Message,), {
  'DESCRIPTOR' : _SCALARSINT64,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarSInt64)
  })
_sym_db.RegisterMessage(ScalarSInt64)

ScalarFloat = _reflection.GeneratedProtocolMessageType('ScalarFloat', (_message.Message,), {
  'DESCRIPTOR' : _SCALARFLOAT,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarFloat)
  })
_sym_db.RegisterMessage(ScalarFloat)

ScalarDouble = _reflection.GeneratedProtocolMessageType('ScalarDouble', (_message.Message,), {
  'DESCRIPTOR' : _SCALARDOUBLE,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ScalarDouble)
  })
_sym_db.RegisterMessage(ScalarDouble)

ArrayUInt32 = _reflection.GeneratedProtocolMessageType('ArrayUInt32', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYUINT32,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArrayUInt32)
  })
_sym_db.RegisterMessage(ArrayUInt32)

ArrayUInt64 = _reflection.GeneratedProtocolMessageType('ArrayUInt64', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYUINT64,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArrayUInt64)
  })
_sym_db.RegisterMessage(ArrayUInt64)

ArraySInt32 = _reflection.GeneratedProtocolMessageType('ArraySInt32', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYSINT32,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArraySInt32)
  })
_sym_db.RegisterMessage(ArraySInt32)

ArraySInt64 = _reflection.GeneratedProtocolMessageType('ArraySInt64', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYSINT64,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArraySInt64)
  })
_sym_db.RegisterMessage(ArraySInt64)

ArrayFloat = _reflection.GeneratedProtocolMessageType('ArrayFloat', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYFLOAT,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArrayFloat)
  })
_sym_db.RegisterMessage(ArrayFloat)

ArrayDouble = _reflection.GeneratedProtocolMessageType('ArrayDouble', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYDOUBLE,
  '__module__' : 'smartsim_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimProtobuf.ArrayDouble)
  })
_sym_db.RegisterMessage(ArrayDouble)


_ARRAYUINT32.fields_by_name['dimension']._options = None
_ARRAYUINT32.fields_by_name['data']._options = None
_ARRAYUINT64.fields_by_name['dimension']._options = None
_ARRAYUINT64.fields_by_name['data']._options = None
_ARRAYSINT32.fields_by_name['dimension']._options = None
_ARRAYSINT32.fields_by_name['data']._options = None
_ARRAYSINT64.fields_by_name['dimension']._options = None
_ARRAYSINT64.fields_by_name['data']._options = None
_ARRAYFLOAT.fields_by_name['dimension']._options = None
_ARRAYFLOAT.fields_by_name['data']._options = None
_ARRAYDOUBLE.fields_by_name['dimension']._options = None
_ARRAYDOUBLE.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
