# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss_protob_array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ss_protob_array.proto',
  package='SmartSimPBArray',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15ss_protob_array.proto\x12\x0fSmartSimPBArray\"6\n\x0b\x41rrayDouble\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x01\x42\x02\x10\x01\"5\n\nArrayFloat\x12\x15\n\tdimension\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x10\n\x04\x64\x61ta\x18\x02 \x03(\x02\x42\x02\x10\x01\x62\x06proto3')
)




_ARRAYDOUBLE = _descriptor.Descriptor(
  name='ArrayDouble',
  full_name='SmartSimPBArray.ArrayDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimPBArray.ArrayDouble.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimPBArray.ArrayDouble.data', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_ARRAYFLOAT = _descriptor.Descriptor(
  name='ArrayFloat',
  full_name='SmartSimPBArray.ArrayFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='SmartSimPBArray.ArrayFloat.dimension', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SmartSimPBArray.ArrayFloat.data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['ArrayDouble'] = _ARRAYDOUBLE
DESCRIPTOR.message_types_by_name['ArrayFloat'] = _ARRAYFLOAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArrayDouble = _reflection.GeneratedProtocolMessageType('ArrayDouble', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYDOUBLE,
  '__module__' : 'ss_protob_array_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimPBArray.ArrayDouble)
  })
_sym_db.RegisterMessage(ArrayDouble)

ArrayFloat = _reflection.GeneratedProtocolMessageType('ArrayFloat', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYFLOAT,
  '__module__' : 'ss_protob_array_pb2'
  # @@protoc_insertion_point(class_scope:SmartSimPBArray.ArrayFloat)
  })
_sym_db.RegisterMessage(ArrayFloat)


_ARRAYDOUBLE.fields_by_name['dimension']._options = None
_ARRAYDOUBLE.fields_by_name['data']._options = None
_ARRAYFLOAT.fields_by_name['dimension']._options = None
_ARRAYFLOAT.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
